language: c
compiler:
  - gcc
  - clang
os:
  - linux


branches:
  only:
    - master

addons:
  apt:
    - libxml2-devel libxml2 libpcap-devel libpcap

script:
  - git submodule init; git submodule update
  - ./bootstrap.sh && ./configure --enable-debug && make clean && make -j5

