language: c
compiler:
  - gcc
os:
  - linux

branches:
  only:
    - master

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-multilib
      - gcc
      - g++
      - autoconf
      - pkg-config
      - make
      - automake
      - libxml2-dev
      - libxml2
      - libpcap0.8-dev
      - libpcap0.8

script:
  - git submodule init; git submodule update
  - ./bootstrap.sh && ./configure && make clean && make -j5

